import type { IconId } from './schemas';

export const ICON_IMPORTS: Record<IconId, () => Promise<{ default: any }>> = {
  folder: () => import('lucide-react').then(m => ({ default: m.Folder })),
  briefcase: () => import('lucide-react').then(m => ({ default: m.Briefcase })),
  user: () => import('lucide-react').then(m => ({ default: m.User })),
  heart: () => import('lucide-react').then(m => ({ default: m.Heart })),
  'dollar-sign': () => import('lucide-react').then(m => ({ default: m.DollarSign })),
  book: () => import('lucide-react').then(m => ({ default: m.Book })),
  lightbulb: () => import('lucide-react').then(m => ({ default: m.Lightbulb })),
  rocket: () => import('lucide-react').then(m => ({ default: m.Rocket })),
  palette: () => import('lucide-react').then(m => ({ default: m.Palette })),
  music: () => import('lucide-react').then(m => ({ default: m.Music })),
  camera: () => import('lucide-react').then(m => ({ default: m.Camera })),
  film: () => import('lucide-react').then(m => ({ default: m.Film })),
  gift: () => import('lucide-react').then(m => ({ default: m.Gift })),
  calendar: () => import('lucide-react').then(m => ({ default: m.Calendar })),
  'shopping-cart': () => import('lucide-react').then(m => ({ default: m.ShoppingCart })),
  map: () => import('lucide-react').then(m => ({ default: m.Map })),
  plane: () => import('lucide-react').then(m => ({ default: m.Plane })),
  tools: () => import('lucide-react').then(m => ({ default: m.ToolCase })),
  code: () => import('lucide-react').then(m => ({ default: m.Code })),
  cpu: () => import('lucide-react').then(m => ({ default: m.Cpu })),
  shield: () => import('lucide-react').then(m => ({ default: m.Shield })),
  trophy: () => import('lucide-react').then(m => ({ default: m.Trophy })),
  chat: () => import('lucide-react').then(m => ({ default: m.ChartArea })),
  clipboard: () => import('lucide-react').then(m => ({ default: m.Clipboard })),
  flag: () => import('lucide-react').then(m => ({ default: m.Flag })),
  star: () => import('lucide-react').then(m => ({ default: m.Star })),
  leaf: () => import('lucide-react').then(m => ({ default: m.Leaf })),
  paw: () => import('lucide-react').then(m => ({ default: m.PawPrint })),
  'heart-pulse': () => import('lucide-react').then(m => ({ default: m.HeartPulse })),
  globe: () => import('lucide-react').then(m => ({ default: m.Globe })),
};
